### ISSUE TITLE
Line continues outside axis

### ISSUE THREAD

**Issue by mpastell** [sisl/PGFPlots.jl#11]
Thanks for very nice package!

I noticed that lines continue outside the axis when I set axis limits. e.g.

`Axis(Plots.Linear(-(1:10)), xmin=2, ymin=-4)`

**Comment by mykelk** [comment]
Wow! That is very strange. Just to see what is going on, I ran these commands
```julia
using TikzPictures
tikzDeleteIntermediate(false)
```
And then I reran your command. I see that both the PDF and SVG that are produced look fine. Even if I open up the SVG in the browser, it looks fine. I suspect that it might have to do with line 214 of TikzPictures.jl, but I'll have to dig into it later. In the meantime, you should be able to save your plots at SVG or PDF without any trouble. It just won't show up in IJulia correctly for now.

**Comment by mykelk** [comment]
I patched TikzPictures.jl, so this can work now. The issue was with the clipping. If you want it to work right now, just to Pkg.checkout("TikzPictures"). I'll tag a release tomorrow so that you can just do Pkg.update().

**Comment by mpastell** [comment]
Thanks for the quick fix!
