### ISSUE TITLE
Incorrect formatting of tick marks

### ISSUE THREAD

**Issue by mpastell** [sisl/PGFPlots.jl#12]
One of the x-axis ticks in this figure shows as  "5 · 10−2" instead of 0.05

![response](https://cloud.githubusercontent.com/assets/430863/5915143/b2c95c2c-a60a-11e4-89d3-686f7734470e.png)

It was produced using:

```julia
using DSP
using PGFPlots
df = digitalfilter(Lowpass(0.4), Butterworth(12))
w = linspace(0, π);
h = freqz(df, w);
p = Axis(Plots.Linear(w/π, 20*log10(abs(h)), style="solid", mark="none"), ymin = -80, xmin = 0,
xlabel=L"x$\pi$rad/sample)", ylabel="Magnitude (db)", width="15cm", height="10cm")
save("response.pdf", p)
```

**Comment by mykelk** [comment]
I agree that looks very strange. However, the pgfplots latex package is responsible for that choice. You can override it using the style options. If you do the following, it will work as you would expect:
```julia
using DSP
using PGFPlots
df = digitalfilter(Lowpass(0.4), Butterworth(12))
w = linspace(0, π);
h = freqz(df, w);
p = Axis(Plots.Linear(w/π, 20*log10(abs(h)), style="solid", mark="none"), ymin = -80, xmin = -1e-6,
xlabel=L"x$\pi$rad/sample)", ylabel="Magnitude (db)", width="15cm", height="10cm", style="xticklabel style={/pgf/number format/fixed}")
```

**Comment by mpastell** [comment]
Thanks for the advice. Would it make sense to set `format/fixed` as a default?

**Comment by mykelk** [comment]
It would be easy to make it the default, but I don't think everyone will always want format/fixed. It would be nice if pgfplots would have an option to make it so that it doesn't mix fixed with scientific on the same axis.
