### ISSUE TITLE
PGFPlots.Image interpolates in IJulia but not when you save

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#18]
If I run:

```julia
p = PGFPlots.Image(imagemat, xrange, yrange)
ax = PGFPlots.Axis(p, xlabel="x", ylabel="y")
PGFPlots.save("temp.pdf", ax)
```

I get a nice PDF in which the image is non-interpolated. If I pass in a 3x3 `imagemat`, I get a nice 3x3 grid in my PDF.

Running:

```julia
p = PGFPlots.Image(imagemat, xrange, yrange)
ax = PGFPlots.Axis(p, xlabel="x", ylabel="y")
```

in IJulia results in the same image being interpolated / smoothed out when it is displayed. Is there a way to have the IJulia output reflect what saving it will do?

**Comment by mykelk** [comment]
I would so love it if someone knew how to fix this. This [link](http://stackoverflow.com/questions/5403955/image-interpolation-mode-in-chrome-safari) may have some clues.

**Comment by tawheeler** [comment]
Oddly enough it shows the correct PDF when you print the page, but not when you generate a print preview.

**Comment by mykelk** [comment]
This now works in modern versions of Chrome with TikzPictures v0.2.4. It doesn't seem to work with FireFox and IE.
