### ISSUE TITLE
Add support for RGB color definitions

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#19]
Tikz doesn't really support direct RGB inputs.
Would it be possible to allow us to define colors in `PGFPlots.jl`?
Perhaps we can create a `define_color` function that will automatically create colors when we generate the LaTeX file:

```TeX
\definecolor{mycolor}{rgb}{1,0.2,0.3}
```

That way we could use:

```julia
define_color("mycolor", [82,227,246])
define_color("my_other_color", 0xFF12AB)
define_color("yet_another_color", myRGB::RGB)

Plots.Linear(x, y, style="mycolor")
```

**Comment by mykelk** [comment]
Updated docs for integer and floating point arrays and added support in code (see 4f5594e0dad9b101df5288effb39c0964d0a9265). Still need to add RGB and UInt32 arguments. Might also want to add cmyk support (see latex [doc](https://en.wikibooks.org/wiki/LaTeX/Colors)).

**Comment by tawheeler** [comment]
Nice! Thank you for adding it so quickly

**Comment by mykelk** [comment]
Full support with documentation now in version 1.2.2. That tag has been merged with METADATA.jl, so a Pkg.update() should work now.
