### ISSUE TITLE
Trailing brackets in labels don't render

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#21]
I recently noticed that trailing brackets in axis labels don't render for me:

```
Axis(Plots.Linear(x, y), xlabel="speed [m/s]")
```

Here the `]` doesn't show up.

I am not sure whether this is a PGFPlots, LaTeXStrings, or LaTeX issue.

**Comment by tawheeler** [comment]
Looks like this might be a LaTeX thing.

**Comment by mykelk** [comment]
I think it is safer to just put the braces in by default. I'll push a fix.
