### ISSUE TITLE
Feature Request: Save to .tex flag to only write out the tikzpicture content

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#23]
One of the best things about PGFPlots is that I can create beautiful plots in Julia and then directly use them in my LaTeX writeups. Right now my workflow is to use `save()` to get a .tex file and then either delete the non-tikzpicture environment code (ie, header and footer) or copy paste the tikzpicture environment into my LaTeX document. Would it be possible to implement a flag for the `save` function that would omit the header?
Alternatively, am I just being dumb and is there a good way to include standalones into a LaTeX document?

**Comment by mykelk** [comment]
Good idea. I'll take care of it.

**Comment by mykelk** [comment]
Done. Required a chance to TikzPictures.jl as well.

**Comment by tawheeler** [comment]
Thanks!
