### ISSUE TITLE
Support histograms with lots of data

### ISSUE THREAD

**Issue by mykelk** [sisl/PGFPlots.jl#26]
Right now, Plots.Histogram relies upon latex to process the raw data. For large data sets, this may cause latex to run out of memory or result in large file sizes. Instead, it would be nice to add an option so that the histogram is computed in Julia (using the `hist` command) and only the coordinates of the histogram are included in the latex file.

**Comment by tawheeler** [comment]
So [Discretizers](http://nbviewer.jupyter.org/github/sisl/Discretizers.jl/blob/master/doc/Discretizers.ipynb) now has code to generate histogram plots. Could be used to solve the problem.

**Comment by tawheeler** [comment]
Check out the discretizers branch!

**Comment by mykelk** [comment]
Looks like there is an issue with Discretizers. Perhaps it needs to be tagged? Here's the error that I'm seeing on 0.4 and 0.5 (as reported by Travis):
```
ERROR: LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Int64}, ::Symbol)
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Int64}, ::Int8)
  convert(::Type{Int64}, ::UInt8)
  ...
 in call at /home/travis/.julia/v0.4/Discretizers/src/disc_uniformwidth.jl:3
```

**Comment by mykelk** [comment]
Might also consider using a name different from "discalg" to something more readable like "discretization".

**Comment by tawheeler** [comment]
Right - Discretizers needed a new tagged release.

**Comment by mykelk** [comment]
Added in f448101109ef848d33f6c77993d6e6587510b41d
