### ISSUE TITLE
No text in Jupyter in firefox?

### ISSUE THREAD

**Issue by pkofod** [sisl/PGFPlots.jl#27]
Try opening http://nbviewer.jupyter.org/github/sisl/PGFPlots.jl/blob/master/doc/PGFPlots.ipynb in firefox. Am I the only one who cannot see text properly? (I can reproduce it in a fresh notebook myself locally).

![firefox](https://cloud.githubusercontent.com/assets/8431156/13760183/18a9e126-ea32-11e5-9a52-59640a7ff399.png)

**Comment by mykelk** [comment]
There seems to be an issue with Firefox. It works fine in Safari, Chrome, and Edge. I'm not sure what is causing the issue. However, if you save the image to a standalone svg, it seems to work in FireFox. See https://github.com/sisl/TikzPictures.jl/issues/13.

**Comment by pkofod** [comment]
Thanks for replying with the other thread, I will continue there.
