### ISSUE TITLE
Bayesian network model 

### ISSUE THREAD

**Issue by DKocacoban** [sisl/PGFPlots.jl#31]
Dear Mykel, 

I am studying on causal bayesian networks. I am planning to use Julia software. However I could not find any manual file which explains working way of codes. As there are limited information about it I cannot apply it for my data set. For Example I want to study alarm data sets and its variables have "True,False" or "Low,Normal,High". However, there is just one example and it is just on bernoulli (true, false). Can you help me about it?  I attached my data set and graph which I want to do. 

![alarm_37_variables](https://cloud.githubusercontent.com/assets/17856437/13815217/a82f5394-eb81-11e5-9683-1ed3900c169c.png)
[Alarmdataset.pdf](https://github.com/sisl/PGFPlots.jl/files/176116/Alarmdataset.pdf)

**Comment by mykelk** [comment]
Thank you so much for your interest! BayesNets.jl is still a work in progress, and we have someone coming in this summer to our lab to help with the documentation and expanding this package to make it more usable for students. In the mean time, we are happy to help and would also appreciate contributions to the documentation and code through pull requests. To answer your question about variables that can take on different values, you probably want to create your CPDs using `CPDs.DiscreteDomain(["Low", "Normal", and "High"])`. @tawheeler might be able to provide a little more detail.

**Comment by tawheeler** [comment]
Here is a simple working example that creates a network VariableA -> VariableB, where VariableA can be Low, Normal, or High and VariableB is Bernoulli.

As Dr. Kochenderfer said, we hope to clean up the API this summer.

Please feel free to make pull requests or code contributions. The BayesNets.jl Github is probably a better place to do that than the PGFPlots repo.

```julia
using BayesNets

bn = BayesNet()

domain_1 = DiscreteDomain(["Low", "Normal", "High"])
add_node!(bn, BayesNetNode(:Variable1, domain_1, CPDs.DiscreteDict(domain_1.elements, Dict{Dict, Vector{Float64}}(
        Dict{Symbol,Any}()   => [0.1, 0.3, 0.6],
    ))))

add_node!(bn, BayesNetNode(:Variable2, BINARY_DOMAIN, CPDs.Bernoulli()))

add_edge!(bn, :Variable1, :Variable2)
set_CPD!(bn, :Variable2, CPDs.Bernoulli(m->begin
        if m[:Variable1] == "Low"
            0.5
        elseif m[:Variable1] == "Normal"
            0.9
        else
            0.2
        end
    end
    ))

println("Prob (Var1=\"Low\",  Var2=true):  ", prob(bn, Dict(:Variable1=>"Low",  :Variable2=>true)))
println("Prob (Var1=\"Low\",  Var2=false): ", prob(bn, Dict(:Variable1=>"Low",  :Variable2=>false)))
println("Prob (Var1=\"High\", Var2=true):  ", prob(bn, Dict(:Variable1=>"High", :Variable2=>true)))
```

**Comment by DKocacoban** [comment]
Dear Tim and Mykel, 
Thank you for your help, but this has not solved my problem totally. I am expecting to get conditional probability table and probability like because it will be harder manually calculating  when a node has more parents. Additionally I want to be able to give random values for discrete and bernoulli domains. I saw program has "rand_discrete_dict()" and "rand_bernoulli_dict()" commands but I do not know how to use them in my study. Please find I have attached two pdfs which show my problem properly. 

Regards,
DKocacoban
[Bayesian_My_Study.pdf](https://github.com/sisl/PGFPlots.jl/files/242652/Bayesian_My_Study.pdf)

[Bayesian_My_expectation.pdf](https://github.com/sisl/PGFPlots.jl/files/242651/Bayesian_My_expectation.pdf)

**Comment by tawheeler** [comment]
Hello DKocacoban,

The `table` problem is occurring here:
`A = ndgrid([domain(bn, name).elements for name in names]...)`

and occurs because the variables in your network have different types. One is of type String, the other of type Bool. This is an issue that needs to be fixed with BayesNets.jl. 
We will be overhauling the package this summer, starting at the end of May.

Your second issue, with `rand`, is caused by having PULMEMBOLUS -> PAP in the graph but giving PULMEMBOLUS a CPD which requires PAP as a parent. We may want to add functionality to automatically check for such inconsistencies.

I will open two issues on BayesNets.jl. Please feel free to post additional issues, but for those related to BayesNets, please post them there.
