### ISSUE TITLE
Is "every mark./append style={rotate=180}" possible?

### ISSUE THREAD

**Issue by pkofod** [sisl/PGFPlots.jl#38]
I know how to make the markers triangles, but I want them pointing down. Is there a way to pass
```
every mark./append style={rotate=180}
```
to the plot?

**Comment by mykelk** [comment]
![image](https://cloud.githubusercontent.com/assets/6294079/14802883/62654c2c-0b09-11e6-8e3e-586316276321.png)

**Comment by pkofod** [comment]
Thanks. I thought I had tried that, but i Think I set the mark using the keywords, maybe that's why.
