### ISSUE TITLE
Require Missing?

### ISSUE THREAD

**Issue by cortner** [sisl/PGFPlots.jl#41]
```
julia> using PGFPlots
INFO: Precompiling module Images...
ERROR: LoadError: ArgumentError: ColorVectorSpace not found in path
 in compilecache at loading.jl:393
```
after manually adding `ColorVectorSpace`, it seems to work

**Comment by mykelk** [comment]
Images is required by PGFPlots, and the more recent versions of Images has ColorVectorSpace required. I think it is possible that you had an older version of Images installed.
