### ISSUE TITLE
Tick mark Control

### ISSUE THREAD

**Issue by cortner** [sisl/PGFPlots.jl#42]
If I understand correctly, control of tick marks is not yet exposed. It would be extremely useful (for me at least) to have this!

**Comment by mykelk** [comment]
Do you have an example in tex of what you'd like to see?

**Comment by cortner** [comment]
Specifically, right now, Id like to
* remove minor ticks
* be able to choose which major ticks are shown
* give custom labels to ticks
Christoph

Sent from my iPhone

On 10 May 2016, at 15:32, Mykel Kochenderfer <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have an example in tex of what you'd like to see?

-

**Comment by cortner** [comment]
I tried to achieve what I want directly using the PGF options string. But the relevant options just seem to be ignored?
```jl
using PGFPlots
x = 0:10
y = sin(x/10*π)
PGFPlots.Plots.Linear(x, y, style="xtick={3, 4, 5}")
```
 What am I doing wrong here ?

**Comment by tawheeler** [comment]
In PGFplots you have two levels for style - in the plots or in the axis.

```
\begin{tikzpicture}
	\begin{axis}[xlabel=Cost, ylabel=Error]
	\addplot[color=red,mark=x] coordinates {
		(2,-2.8559703)
		(3,-3.5301677)
	};
	\end{axis}
\end{tikzpicture}
```

Above you can see the two locations. (1) after \addplot for the each individual plot (line plot, in this case) and (2) after `\begin{axis}` for the overall axis. The axis labels and ticks are specified in the axis, so you need to put that there.

```
using PGFPlots
x = 0:10
y = sin(x/10*π)
Axis(PGFPlots.Plots.Linear(x, y), style="xtick={3, 4, 5}")
```

**Comment by cortner** [comment]
thank you - that was rather naive of me.

**Comment by cortner** [comment]
before dropping this issue completely: is there a plan to expose options like this via kw arguments, or is the preference to keep it all in the `style` string? If it doesn't interfere, then I could try myself.

**Comment by mykelk** [comment]
I think it would be very nice to have control over the ticks. It should not be too hard to implement. Feel free to send in a PR.

**Comment by martin-fzd** [comment]
> In PGFplots you have two levels for style - in the plots or in the axis.
> 
> ```
> \begin{tikzpicture}
>     \begin{axis}[xlabel=Cost, ylabel=Error]
>     \addplot[color=red,mark=x] coordinates {
>         (2,-2.8559703)
>         (3,-3.5301677)
>     };
>     \end{axis}
> \end{tikzpicture}
> ```
> 
> Above you can see the two locations. (1) after `\addplot` for the each individual plot (line plot, in this case) and (2) after `\begin{axis}` for the overall axis. The axis labels and ticks are specified in the axis, so you need to put that there.
> 
> ```
> using PGFPlots
> x = 0:10
> y = sin(x/10*π)
> Axis(PGFPlots.Plots.Linear(x, y), style="xtick={3, 4, 5}")
> ```

Because I have a similar issue, I want to reopen this.
I think the { } vector syntax is discontinued in Julia. Is there a good way to pass a vector containing the desired ticks to the axis?

**Comment by tawheeler** [comment]
The {} in this case is in a string, so you don't actually use Julia to construct an array.
If you have an array you have to transform it into a string.
