### ISSUE TITLE
Support png output?

### ISSUE THREAD

**Issue by tbreloff** [sisl/PGFPlots.jl#45]
What would it take to allow writing PNG data for PGFPlots?  This would allow for lots of stuff in Plots (including proper regression testing), and would probably make https://github.com/sisl/PGFPlots.jl/issues/40 unnecessary, though maybe with png support you'd get both Plots and Reel animations for free.

**Comment by mykelk** [comment]
I think it could be done with [ImageMagick.jl](https://github.com/JuliaIO/ImageMagick.jl). You'd probably want to convert from PDF to PNG.

**Comment by tbreloff** [comment]
That's true... perhaps I should implement a generic method to do this in Plots, so that any backends that don't have png (but do have something else) can be supported.

**Comment by mykelk** [comment]
That might be nice. Of course, if you want to file a PR here to support writing to PNG, we're happy to merge it in.

**Comment by tbreloff** [comment]
If I thought that was easier I'd certainly do it ;)

**Comment by tbreloff** [comment]
It's working!  I used FileIO (which probably uses ImageMagick).  Thanks for the suggestion!

![tmp](https://cloud.githubusercontent.com/assets/933338/15946363/98e1bfbe-2e64-11e6-94b2-fe199ccd524c.gif)

There are some weird artifacts though... I'm not quite sure what's causing them.  The svg output certainly looks nicer.

**Comment by mykelk** [comment]
Awesome!

**Comment by tbreloff** [comment]
This is what the svg looks like... any idea how I can force the background to white (instead of transparent)?

![tmp](https://cloud.githubusercontent.com/assets/933338/15947032/76fbb2c6-2e67-11e6-9e45-d85701de2d18.png)

ps-- That's a screenshot of REPL plotting :)

**Comment by tbreloff** [comment]
I expect the transparency is why there was weirdness with PNGs

**Comment by tbreloff** [comment]
I can finally generate examples: http://plots.readthedocs.io/en/latest/examples/pgfplots/

**Comment by tawheeler** [comment]
Nice!
* how are you plotting from the REPL? (Calling eog or similar?)
* does this mean you got transparencies to work?

**Comment by tbreloff** [comment]
> how are you plotting from the REPL?

Calling [open_browser_window](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/web.jl#L22) on a saved SVG file.


> does this mean you got transparencies to work?

No. The background (outside of the plotting area) is still transparent... it's just hard to tell on a white background.  Any idea how to set that? (if not, I'll slog through the docs eventually)

**Comment by tawheeler** [comment]
It looks like pdf2svg creates a transparent background for web viewing.
You could try adding `-background white` to `save(f::SVG, tp::TikzPicture)` in TikzPictures.jl and see if that fixes the problem.
