### ISSUE TITLE
Support for a custom preamble.

### ISSUE THREAD

**Issue by KristofferC** [sisl/PGFPlots.jl#52]
It is common to want to use external latex package functions when creating labels and titles (like `\bm` to get bold greek letters). This requires the ability to be able to include a custom preamble into the TikzPicture that is appended to the standard one. Maybe both `plot` and `save` could include an optional field `custom_preamble::String = ""`. An alternative method could be to have a global variable like `_pgfplotsoptions` and let the user add lines to that one.

**Comment by mykelk** [comment]
Are you looking for something like this?
```julia
pushPGFPlotsPreamble("\\usepackage{cmbright}")
```
That is currently supported.

**Comment by KristofferC** [comment]
Oh I must have misses that. Sorry!
