### ISSUE TITLE
Support for error bars in Linear

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#54]
Would be good to have eventually.

**Comment by mykelk** [comment]
There is an undocumented ErrorBars type. See code in src/plots.jl.

**Comment by mykelk** [comment]
It would be nice if it wasn't its own type, maybe. It might be nice to have error bars be a property of `Linear`.

**Comment by zsunberg** [comment]
We need a way to set the error bar style independently of the plot style. For example, if you make the line dashed, it also tries to make the error bars dashed.  I tried to put together a pull request to fix that, but I could not figure out how the optionHelper and associated "map"s were supposed to work.

Might be easier to maintain in the future if we combined this into Linear.

**Comment by mykelk** [comment]
I added this functionality in a5846bc5000492a9430562dad886e859bda6c397. Check out the docs for the interface. @tawheeler if you like it, then go ahead and tag a release and close this issue.

**Comment by tawheeler** [comment]
Nice! Created a [PR](https://github.com/JuliaLang/METADATA.jl/pull/6620)
