### ISSUE TITLE
Would be nice to avoid the lualatex85.sty error

### ISSUE THREAD

**Issue by zsunberg** [sisl/PGFPlots.jl#55]
Whenever there is an error compiling the document, the only error message I see is
```
LaTeX Error: File `luatex85.sty' not found.
```
but the error never has anything to do with luatex85. If I compile the .tex in the terminal, I can usually figure out what the problem is. It would be nice if we could allow latex to dump all of its output so that the real error can be found.

Maybe this issue should be filed in the TikzPictures package?

**Comment by mykelk** [comment]
Yeah, it should be in TikzPictures.

**Comment by zsunberg** [comment]
refiled in tikzpictures
