### ISSUE TITLE
Support for dataframes

### ISSUE THREAD

**Issue by mykelk** [sisl/PGFPlots.jl#58]
Since DataFrames.jl no longer conflicts with Images.jl (as of Julia 0.5), I'd like to suggest adding some convenience constructors that take DataFrames as input, similar to Gadfly.jl. Unfortunately, Julia 0.4 will still generate warnings, but I hope that most users will start moving towards Julia 0.5 anyway.

**Comment by tawheeler** [comment]
Something along the lines of:

```
Linear(dataframe, x=:x, y=:y)
Linear3(dataframe, x=:x, y=:y, z=:z)
Scatter(dataframe, x=:x, y=:y)
Histogram(dataframe, x=:x)
Histogram2(dataframe, x=:x, y=:y)
```

Maybe we can figure something out for Quiver.

One consideration is whether we want to support `Linear(dataframe, x=:x, y=:y)` or `Linear(dataframe; x=:x, y=:y)`. I think I prefer the second one with explicit x and y designations.

**Comment by mykelk** [comment]
Yep, I also prefer the second one.

**Comment by tawheeler** [comment]
```
INFO: Precompiling module PGFPlots.
WARNING: both Plots and DataFrames export "Histogram"; uses of it in module PGFPlots must be qualified
ERROR: LoadError: UndefVarError: Histogram not defined
```
