### ISSUE TITLE
Histogram2 should be produce a Patch2D

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#60]
- Histogram2 currently produces an `Image`, there is no actual `Histogram2` type so imo we should not use an uppercase function that makes people think it is a type
- Images require evenly-spaced bins. If we use a rectangular Patch2D we can have unevenly spaced bins.
- If we want, we can also create hex bins using triangle patches

**Comment by mykelk** [comment]
The 2D histogram as an image is super useful and used by a bunch of people, so we should carefully consider how we change things. A desirable property of calling it Histogram2 is that it is clear how to interpret the inputs (i.e., a bunch of datapoints). Using an image is sometimes way more efficient than using patches (in terms of rendering and filesize). Maybe we have these options:

1. We create a real Histogram2 type and we can have a field that determines whether it is rendered as a patch or as an image or even hexbins?
2. We create a function histogram2 that takes some arguments that will construct either a Patch2D or Image or HexBin objects?
3. Same as 2, but we just call it Histogram2 to convey the fact that we are constructing something new. The fact that it is actually a Patch2D or Image doesn't matter to the user.

**Comment by tawheeler** [comment]
Keeping histogram2 images is definitely a good idea when data is in a regular grid.
We could have a Histogram2D(data, edges x, edges y) which would allow for uneven binning and could produce a Patch2D.
Would a HexBin be its own object?

**Comment by mykelk** [comment]
Yeah, HexBin would be its own thing. Histogram2D can return a patch if edges are supplied and an image if not; it could dispatch on the type of the arguments. (At least that's one idea.)
