### ISSUE TITLE
direct support for mark color in Linear

### ISSUE THREAD

**Issue by jdonnert** [sisl/PGFPlots.jl#63]
is there support planned to be able to change the color of the marker in Plots.Linear by directly supporting the PGFPlots keyword : mark color={⟨color⟩}  ?

I know that it is possible to achieve the same through a combination of Plots.Scatter and Plots.Linear. However, a simple keyword like this : markColor="green"  would make things much easier and is consistent with the backend.

julius

**Comment by mykelk** [comment]
We currently support something like this:
![image](https://cloud.githubusercontent.com/assets/6294079/19986342/87f3edf2-a1d3-11e6-90db-867e8388ee9f.png)
Does this fulfill your need?

**Comment by jdonnert** [comment]
Yes it does indeed, Thank you ! 

 I was not aware of the option, I started using the package a week ago. Maybe it is worth adding this to the documentation in a more explicit way...

**Comment by mykelk** [comment]
Yay! Yeah, you can pass pretty much any option through the style command. It isn't exactly feasible to enumerate all the possible options supported by PGFPlots (the manual is 544 pages), but I think it would be good for us to enhance the documentation with some more common options and examples.
