### ISSUE TITLE
\text does not work in labels

### ISSUE THREAD

**Issue by tawheeler** [sisl/PGFPlots.jl#65]
In LaTeX math mode one can use `\text{stuff}` to render `stuff` as text.
For some reason this does not work with PGFPlots labels.

```
using PGFPlots
Axis(Plots.Linear([1,2], [1,2]), xlabel=L"\text{hi}")
```

```
! Undefined control sequence.
<recently read> \text 
```

Also:

```
Axis(Plots.Linear([1,2], [1,2]), xlabel="\$\\text{hi}\$")
```

```
! Undefined control sequence.
<recently read> \text 
```

**Comment by mykelk** [comment]
It's because the `\text` command requires the amsmath package. You can get what you want by doing this:
```julia
pushPGFPlotsPreamble("\\usepackage{amsmath}")
```
Might be worth including this example in the documentation.
