### ISSUE TITLE
Package cmbright.sty fails in test

### ISSUE THREAD

**Issue by mykelk** [sisl/PGFPlots.jl#66]
Travis fails with this:
```
LaTeX Error: File `cmbright.sty' not found.
```
There is an example in the notebook that shows how you can use this package. It looks like something needs to be added to `.travis.yml` to get this package included. Or we can just use a different example in the notebook.

**Comment by tawheeler** [comment]
Weird. I added a new cell that uses amsmath, the cmbright cells already existed.
Switched to xfrac in e9d8633.
