### ISSUE TITLE
save *.tikz function

### ISSUE THREAD

**Issue by hofmannmartin** [sisl/PGFPlots.jl#72]
I have been using the package to some extend to generate plots.

It would be interesting to be able to save the plot as `.tikz` file by stripping code down to the `tikzpicture` environment.

**Comment by mykelk** [comment]
Well, actually, can't this be done right now with:
```julia
p = Plots.Histogram(rand(10))
save("myfile.tex", p, include_preamble=false)
```

**Comment by hofmannmartin** [comment]
I was not aware of this. Thank you :+1: 

Any way just for convenience I would like to be able to 
```julia
save("myfile.tikz", p)
```
This helps a lot keeping everything organized, when writing a document for example.

I did manage to bring this to work, but this requires some changes to the `TikzPictures` package at first. I did just make a pull request there.

**Comment by hofmannmartin** [comment]
have opened up a pull request, which allows

```julia
save("myfile.tikz", p)
```

**Comment by mykelk** [comment]
Thanks! Merged. Sorry for the delay.
