### ISSUE TITLE
not working on Mac

### ISSUE THREAD

**Issue by mkborregaard** [sisl/PGFPlots.jl#76]
Is it correctly understood that this package, and thus it's Plots backend) does not work on Mac (which doesn't have pdf2svg which is required by TikzPictures)?

**Comment by mykelk** [comment]
It works on Mac. In fact most of my students use it on Mac. You just need to install pdf2svg.

**Comment by mkborregaard** [comment]
Right, just found it on Homebrew. Sorry for the noise.

**Comment by mkborregaard** [comment]
I just read the description in the docs detailing how you could get it in Ubuntu and Windows, and couldn't find any description of a Mac version on the interwebs.

**Comment by mkborregaard** [comment]
I'd do a PR describing the Homebrew download on the docs, but PR'ing a new Jupyter notebook might be messy?

**Comment by mkborregaard** [comment]
Could Homebrew.jl download it automagically when Pkg.add?

**Comment by mykelk** [comment]
Yes, I think it could be done automagically. It would be great to have a PR.
