### ISSUE TITLE
install error again?

### ISSUE THREAD

**Issue by nizhizhen** [sisl/PGFPlots.jl#81]
![2017-09-02 10-46-33](https://user-images.githubusercontent.com/19453340/29992339-0d241c22-8fcc-11e7-82c8-25031a76536f.png)

could you show me the detail process.

**Comment by mykelk** [comment]
Can you include the full command that generated this error?

**Comment by nizhizhen** [comment]
using Compose,DataFrames,DataFramesMeta,LaTeXStrings
using Plots,StatPlots,RecipesBase
#,PlotThemes,PlotUtils,PlotRecipes
pgfplots()
#
df = readtable("f_in.csv")
df=@select(df,months=:months,species=:species,sites=:sites,x1=:x2013,x2=:x2014,x3=:x2015,x4=:x2016)

pm25=@where(df,:species.=="PM25")[:,[:x1, :x2,:x3,:x4]]
so2=@where(df,:species.=="SO2")[:,[:x1, :x2,:x3,:x4]]
no2=@where(df,:species.=="NO2")[:,[:x1, :x2,:x3,:x4]]

a=groupedbar(df[:months],Array(pm25),bar_width=0.7,bar_position=:dodge,
            label=["2013","2014","2015","2016"],legendfont=Plots.font(7),legend=:none,
          title="(a)",titlepos=:left,titlefont=Plots.font(11),
               yaxis=("Concentration (\\mug m^{-3})",(0,100),0:25:100,Plots.font(8))
      )




results:

! I can't find file `xkeyval'.
l.39 \ifx\XKeyValLoaded\endinput\else\input xkeyval 
                                                  \fi
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
! Emergency stop.
l.39 \ifx\XKeyValLoaded\endinput\else\input xkeyval 
                                                  \fi
End of file on the terminal!



Here is how much of LuaTeX's memory you used:
 92 strings out of 494577
 100000,89155 words of node,token memory allocated 245 words of node memory still in use:
   1 dir, 2 glue, 32 glue_spec, 1 if_stack nodes
   avail lists: 2:11,3:1,4:1
 4230 multiletter control sequences out of 65536+600000
 14 fonts using 591559 bytes
 19i,0n,12p,128b,15s stack positions out of 5000i,500n,10000p,200000b,100000s
!  ==> Fatal error occurred, no output PDF file produced!

Error saving as SVG

**Comment by nizhizhen** [comment]
bar_width=0.7  has removed

**Comment by mykelk** [comment]
It looks like the latex package called `xkeyval` was not installed. You can install this using `tlmgr` or, if you installed latex on ubuntu, you can run a command like `sudo apt-get install texlive-latex-recommended`.

**Comment by nizhizhen** [comment]
nzz@nzz-PC:~$ sudo apt-get install texlive-latex-recommended
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
texlive-latex-recommended 已经是最新版 (2016.20170123-5)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。


they mean the texlive has been installed with lasted version

**Comment by nizhizhen** [comment]
nzz@nzz-PC:~$ tlmgr
(running on Debian, switching to user mode!)
tlmgr: no action given; try --help if you need it.
nzz@nzz-PC:~$

**Comment by mykelk** [comment]
You might want to try the second post [here](https://ubuntuforums.org/showthread.php?t=1499573).

If you want to use `sudo tlmgr install xkeyval`. If that doesn't work, you might want to use this script to properly install `texlive` on ubuntu: https://github.com/scottkosty/install-tl-ubuntu.

**Comment by nizhizhen** [comment]
trouble you again ,  things still go wrong after the texlive installed as your web

! I can't find file `xkeyval'.
l.39 \ifx\XKeyValLoaded\endinput\else\input xkeyval 
                                                  \fi
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
! Emergency stop.
l.39 \ifx\XKeyValLoaded\endinput\else\input xkeyval 
                                                  \fi

**Comment by mykelk** [comment]
After you ran the `install-tl-ubuntu`, did you then run `sudo tlmgr install xkeyval`?

**Comment by nizhizhen** [comment]
sudo tlmgr install xkeyval
(running on Debian, switching to user mode!)
Cannot determine type of tlpdb from /home/nzz/texmf!
cannot setup TLPDB in /home/nzz/texmf at /usr/bin/tlmgr line 5713.

**Comment by nizhizhen** [comment]
I have run the install-tl-ubuntu   then .  sudo tlmgr install xkeyval errors

**Comment by mykelk** [comment]
I think we're no longer discussing PGFPlots.jl but rather texlive installation issues. I'll close this issue since your issue is better resolved in a forum like https://tex.stackexchange.com.
