### ISSUE TITLE
Plots.Scatter is now returning Plots.Linear?

### ISSUE THREAD

**Issue by sbromberger** [sisl/PGFPlots.jl#83]
I'm pretty sure this changed recently, as my code is now failing (though a git blame doesn't show any recent changes to the constructor):

```
julia> x = [1:10;]; y = [1:10;];

julia> Plots.Scatter(x,y)
PGFPlots.Plots.Linear(Real[1 2 … 9 10; 1 2 … 9 10], nothing, nothing, nothing, nothing, true, nothing)
```

I'm fairly sure this used to return a `Plots.Scatter`.

**Comment by mykelk** [comment]
Strange. It looks like there is currently the following in the `Scatter` constructor:
```julia
    function Scatter{T<:Any}(data::AbstractMatrix{T}; mark=nothing, markSize=nothing, style=nothing, onlyMarks=true, legendentry=nothing, scatterClasses=nothing)
        if size(data,1) == 2
            return Linear(data, mark=mark, markSize=markSize, style=style, onlyMarks=onlyMarks, legendentry=legendentry)
        else
            return new(data, mark, markSize, style, legendentry, onlyMarks, scatterClasses)
        end
    end
```
So, depending on the shape, it might just return a Linear object. I'm not sure what the rationale for this was. Perhaps @tawheeler knows?

**Comment by MageekDM** [comment]
Linear objects generate \addplot[stuff] whereas Scatter objects generate \addplot[scatter, stuff]. For 2d scatter plots without other features specified per point (like node size or color) you can just use a Linear with "draw=none".
That seems to be the rationale.
This definitely violates the principle that functions with the same name as a type should construct that type.
I think we discussed using a "scatter" function instead for the Linear version.

**Comment by tawheeler** [comment]
Linear objects generate \addplot[stuff] whereas Scatter objects generate \addplot[scatter, stuff]. For 2d scatter plots without other features specified per point (like node size or color) you can just use a Linear with "draw=none".
That seems to be the rationale.
This definitely violates the principle that functions with the same name as a type should construct that type.
I think we discussed using a "scatter" function instead for the Linear version.

**Comment by mykelk** [comment]
It seems like we have a few options:
1. Change it to just return a Scatter. Sure, Scatter doesn't really provide much additional functionality beyond linear, but it will maintain backwards compatibility.
2. Change Scatter to a scatter function.
3. Get rid of Scatter in favor of Linear. Advantage being that there are fewer concepts to keep track of, but it will break backwards compatibility.

**Comment by tawheeler** [comment]
fwiw, Scatter was originally introduced this way (https://github.com/sisl/PGFPlots.jl/commit/724f475c8c58ccbc9d1a10134167b577a80318c9)

**Comment by tawheeler** [comment]
Can't do the convert - scatter with 3 or more values has (x,y) [attribute]. Just keeping the original `plotHelper` function for `Scatter`.
