### ISSUE TITLE
BarChart not defined

### ISSUE THREAD

**Issue by chelseas** [sisl/PGFPlots.jl#84]
I tried creating a bar chart but got the error "BarChart not defined":

Plots.BarChart(["cat", "dog"])
ERROR: UndefVarError: BarChart not defined

I am using Julia 0.5.0 on mac OSX

**Comment by tawheeler** [comment]
I think you need Julia 0.6 for a version of PGFPlots that supports the `BarChart` type.
You can still get a bar chart using a `Linear`, use style = "const plot, mark=none".
