### ISSUE TITLE
PGFPlot is showing an additional factor on the axis

### ISSUE THREAD

**Issue by tamasgal** [sisl/PGFPlots.jl#86]
Dear all,

I am not able to figure out why there is this additional factor (*1e7) shown on the bottom right. This is confusing and obviously wrong. Any ideas?

MWE:
```
using Plots; pgfplots()
plot(histogram(rand(10000)*1e7))
```

Cheers,
Tom

![PGFPlot with wrong axis factor](https://user-images.githubusercontent.com/1730350/34160948-37c3e9be-e4cf-11e7-86e3-1ec1e62c072c.png)

**Comment by mbaz** [comment]
The problem may be in the Plots package, not PGFPlots.
```
using PGFPlots
d=(rand(10000)*1e7);
f=Axis(Plots.Histogram(d, bins=20), ymin=0);
```
produces a plot with correct axes.

**Comment by tamasgal** [comment]
Yep, this will be discussed further in Plots.jl. Thanks!
