### ISSUE TITLE
xtick and xticklabels

### ISSUE THREAD

**Issue by tbeason** [sisl/PGFPlots.jl#88]
For a Linear plot, I've been trying to find a way to change the ticklabels using PGFPlots. So far, I haven't been successful. It would be cool if these options could be added in.

I see in the docs there is something about a `customOptions` keyword, but it doesn't look like there is any such thing implemented.

**Comment by tawheeler** [comment]
How about:
```
Axis(Plots.Linear([1,2,3], [4,5,6]), style="xtick={1.5,2.7}, xticklabels={hi, there}")
```

**Comment by tbeason** [comment]
Ah ok that works. It is a bit dirty though. Would be helpful I suppose to mention in the docs. Does that trick work for all pgfplots options that aren't explicitly given PGFPlots keywords?

**Comment by tawheeler** [comment]
Yes, `style` for Plots elements, `GroupPlot`, and `Axis` all allow you to pass in a string in the traditional tikz fashion. There is also a `Plots.Command` for more control over entries.

There was a push to construct a more rigid, tikz-data-structured version of PGFPlots. See https://github.com/sisl/PGFPlots.jl/issues/69
