### ISSUE TITLE
Variables in legendentries

### ISSUE THREAD

**Issue by nishaChandramoorthy** [sisl/PGFPlots.jl#90]
If this is a feature already, could you please tell me how to use variable names in 
legend entries? For instance,

``a = Axis(Plots.Linear(x, y[:,1], legendentry=L"$10^{-1}$")) ``
``for k = 2:N``
	``push!(a, Plots.Linear(x, y[:,k], legendentry=L"$10^{-\k}$"))``
``end	``

In the above, I want ``\k`` to be the loop variable ``k``.
I apologize if it's indeed mentioned in the documentation and I missed it!

**Comment by tawheeler** [comment]
You can use julia string interpolation without the L macro:

push!(a, Plots.Linear(x, y[:,k], legendentry="\$10^{-$k}\$")

**Comment by mykelk** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/6294079/37298752-7853ff82-25de-11e8-87ff-f9d4cca4ffb9.png)

**Comment by nishaChandramoorthy** [comment]
Thanks a lot!
