### ISSUE TITLE
Remove temporary image when saving Plots.Image pdf

### ISSUE THREAD

**Issue by smthorn** [sisl/PGFPlots.jl#92]
Whenever I save a pdf using Plots.Image, it creates a temporary image in the same directory. I know I can specify a filename, but I would like the output to be contained in the pdf without superfluous images littering the directory. Am I not setting something correctly?

Thank you!

**Comment by mykelk** [comment]
You can delete the image. It gets embedded in the PDF; there are no external dependencies.

**Comment by smthorn** [comment]
True, but it would be nice if it were automagically removed, thus saving the end user that extra step every time a new pdf is created.

**Comment by mykelk** [comment]
Ah, I think we're just missing a call to `cleanup` in the `save` function within `src/PGFPlots.jl`. Before submitting a PR, of course, double check that it works.

**Comment by mykelk** [comment]
Should be fixed now.
