### ISSUE TITLE
Centos7 lualatex problems

### ISSUE THREAD

**Issue by mmikhasenko** [sisl/PGFPlots.jl#93]
I leave it here for anyone who meets the same problem.

```julia
using Plots
pgfplots()
plot(x->sin(x),0,1)
```
throws the error:
```
! LuaTeX error .../texlive/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua:55: b
ad argument #1 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	.../texlive/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua:55: in main chunk
	[C]: in function 'dofile'
	[string "\directlua "]:6: in main chunk.
l.139   }
       %
Error saving as SVG
LaTeX error
```
It comes down to the `TikzPictures` call `save(PDF("test"), ...)`,
which runs `lualatex file.tex` and fails.

It seems that there is the `lualatex` problem with `package.loaders` which does not exist any longer as discussed here http://tug.org/pipermail/luatex/2013-January/003987.html
or something like this. I could not fix it.

`luatex --version` => `LuaTeX, Version beta-0.76.0-2015112013  (TeX Live 2013) (rev 4627)`
installed via `yum` from the repository http://jnovy.fedorapeople.org/texlive/2012/packages.f17/

__The problem was solved by installing the TeX Live-2017!__
The installation process is described here:
https://www.systutorials.com/241660/how-to-install-tex-live-on-centos-7-linux/

**Comment by mykelk** [comment]
Thanks! Yes, this was a known issue fixed in more recent versions.
