### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by jcrbloch** [sisl/PGFPlots.jl#96]
My code is:
```
using PGFPlots
p=plot(x->exp(-x^2/2),(-5.0,5.0))
save("test1.pdf",p)
```
The error is:
MethodError: no method matching cleanup(::TikzPictures.TikzPicture)
Closest candidates are:
  cleanup(::PGFPlots.Plots.Contour) at /Users/bloch/.julia/v0.6/PGFPlots/src/PGFPlots.jl:706
  cleanup(::PGFPlots.Plots.Image) at /Users/bloch/.julia/v0.6/PGFPlots/src/PGFPlots.jl:705
  cleanup(::PGFPlots.Plots.Command) at /Users/bloch/.julia/v0.6/PGFPlots/src/PGFPlots.jl:704

**Comment by jcrbloch** [comment]
Adding a line in PGFPlots.jl solves the problem:
`PGFPlots.cleanup(p::TikzPictures.TikzPicture) = nothing`

**Comment by mykelk** [comment]
For some reason, a recent commit removed that. I'll fix it now.

**Comment by mykelk** [comment]
Actually, you want to replace your second line with:
```julia
p=Plots.Linear(x->exp(-x^2/2),(-5.0,5.0))
```
This is because the `plot` function returns a `TikzPicture`.

**Comment by mykelk** [comment]
`Plots.Linear` is just a constructor. It's a type of plot. A `TikzPicture` is just what one of these plots turns into when we plot them.
